In [7]:
import tensorflow as tf
print("TensorFlow imported successfully")

TensorFlow imported successfully


In [8]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.21.0


In [9]:
import tensorflow as tf
scalar = tf.constant(10)
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [10]:
vector = tf.constant([10,25,30])
print(vector)

tf.Tensor([10 25 30], shape=(3,), dtype=int32)


In [11]:
matrix = tf.constant([
    [1,2],
    [3,4]
])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [12]:
tensor_3d = tf.constant([[[1, 2],[3,4]],[[5,6],[7,8]]])

print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [13]:
a = tf.constant([10,20])
b = tf.constant([30,40])

print(tf.add(a,b))

tf.Tensor([40 60], shape=(2,), dtype=int32)


In [14]:
print(tf.subtract(a,b))

tf.Tensor([-20 -20], shape=(2,), dtype=int32)


In [15]:
print(tf.multiply(a,b))

tf.Tensor([300 800], shape=(2,), dtype=int32)


In [16]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[5,6],[7,8]])
print(tf.matmul(matrix1,matrix2))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [17]:
tensor = tf.constant([1,2,3,4,5,6])
reshaped = tf.reshape(tensor,(2,3))
print(reshaped)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [18]:
import numpy as np
array = np.array([10,20,30])

tensor = tf.convert_to_tensor(array)

print(tensor)

tf.Tensor([10 20 30], shape=(3,), dtype=int64)
